### ISSUE TITLE
Expected date to release the code

### ISSUE THREAD

**Issue by carlosedubarreto** [lizhe00/AnimatableGaussians#1]
Hello, is there a date expected to release the code?

This work looks amazing!!!

**Comment by lizhe00** [comment]
Hi, thanks for your attention! The code will be available upon the paper acceptance.

**Comment by jerrymatjila** [comment]
I fell off my chair reading this paper. This is amazing! Wow!

**Comment by lizhe00** [comment]
> I fell off my chair reading this paper. This is amazing! Wow!

Thanks for your comment! And watch your chair, haha! 😆

**Comment by yangqinhui0423** [comment]
Looking forward to the day the code is released!

**Comment by lizhe00** [comment]
Hi everyone, the code has been released. Welcome to have a try!
@carlosedubarreto @jerrymatjila @yangqinhui0423

**Comment by xkkjiayou** [comment]
感谢您的来信，此时我不在办公室，稍后会及时阅读。在此期间我不方便接收邮件。如果您想及时获得通讯，请拨打我的手机联系我，谢谢您。

**Comment by jerrymatjila** [comment]
> Hi everyone, the code has been released. Welcome to have a try! @carlosedubarreto @jerrymatjila @yangqinhui0423

Thank you @lizhe00

**Comment by carlosedubarreto** [comment]
> Hi everyone, the code has been released. Welcome to have a try! @carlosedubarreto @jerrymatjila @yangqinhui0423

Thanks a lot for the info. Now I'll have to carve some time to test LOL.
