### ISSUE TITLE
AvatarRex数据集中的cano_smpl_pos_map.exr和init_pts_lbs.npy我该如何获得？在network.avatar.py中的第27行和31行中有引用

### ISSUE THREAD

**Issue by zhangdanq** [lizhe00/AnimatableGaussians#11]
https://github.com/lizhe00/AnimatableGaussians/blob/4441d7b383a7e7d38624660fc65713c92e9c800e/network/avatar.py#L27
https://github.com/lizhe00/AnimatableGaussians/blob/4441d7b383a7e7d38624660fc65713c92e9c800e/network/avatar.py#L31

**Comment by lizhe00** [comment]
https://github.com/lizhe00/AnimatableGaussians/blob/master/README.md#data-preparation

**Comment by liwenssss** [comment]
Just to confirm, do we need to generate the cano_smpl_pos_map for the AvatarRex dataset following the steps mentioned in GEN_DATA.md? I thought the provided link in PREPROCESSED_DATASET.md already includes it.....

**Comment by liwenssss** [comment]
> Just to confirm, do we need to generate the cano_smpl_pos_map for the AvatarRex dataset following the steps mentioned in GEN_DATA.md? I thought the provided link in PREPROCESSED_DATASET.md already includes it.....

Sry, I solve the problem.. I confused the link between the raw data and the processed data..
