### ISSUE TITLE
Relightable models

### ISSUE THREAD

**Issue by taconite** [lizhe00/AnimatableGaussians#28]
Hi,

Thank you for your amazing work!

I noticed that you recently updated your website/github for relightable models. Any plan to release either the code or a technical report for the relightable models?

best

**Comment by lizhe00** [comment]
Hi Shaofei,

Thanks for your interest! We may release the code of relighting in the future. We tried submitting the manuscript to arXiv, but it failed many times. We may release the manuscript by updating [the conference version](https://arxiv.org/abs/2311.16096) in the next few days.

Thanks!

**Comment by taconite** [comment]
Thanks for your answer! Looking forward to reading the manuscript :)

**Comment by lizhe00** [comment]
Hi, our manuscript is available [here](https://arxiv.org/pdf/2311.16096) now.
