### ISSUE TITLE
Change the resolution of frames

### ISSUE THREAD

**Issue by silence-tang** [lizhe00/AnimatableGaussians#38]
你好，如果我想将这些视频帧处理成512x512分辨率，应该怎么做呢？这是否涉及到相机参数或者smplx参数的修改？
谢谢！

**Comment by lizhe00** [comment]
yaml文件里img_scale改成0.5

**Comment by silence-tang** [comment]
多谢回复。我的理解”yaml文件里img_scale改成0.5”应该是让测试的时候渲染出512x512的结果对吧？
我之前的表述可能不太清楚，其实我想请教的是，我的方法需要512x512的图像去训练，但THuman4.0提供的图像是1330x1150，所以现在的问题是1. 如何把1330x1150的图像合理地处理成512x512。2. 如何相应地调整相机的内(外)参使其符合处理后得到的512x512的图像。
期待解答，谢谢~

**Comment by lizhe00** [comment]
根据相机投影模型u=fx/z*x+cx修改，fx的变化取决于缩放倍数，cx取决于你的裁剪，可以自己推导一下
