### ISSUE TITLE
How to get the files needed in comparison_body_only_avatars.py

### ISSUE THREAD

**Issue by silence-tang** [lizhe00/AnimatableGaussians#39]
Hi, I want to run comparison_body_only_avatars.py but don't know how to get the needed files, for example `./test_results/subject00/...`
Could you provide these files? Thanks a lot!

**Comment by silence-tang** [comment]
你好，其实我是想快速计算一下AnimatableGaussians的指标，但我的计算方式可能和comparison_body_only_avatars.py里面的有所不同，所以希望您可以提供一下AnimatableGaussians在THUman4.0 subject00的2000~2500帧上的cam18的novel pose结果（'./test_results/subject00/styleunet_gaussians3/testing__cam_%03d/batch_750000/rgb_map'），不知道可不可以呢？这对我帮助很大，多谢~

**Comment by lizhe00** [comment]
> 你好，其实我是想快速计算一下AnimatableGaussians的指标，但我的计算方式可能和comparison_body_only_avatars.py里面的有所不同，所以希望您可以提供一下AnimatableGaussians在THUman4.0 subject00的2000-2500帧上的cam18的novel pose结果，不知道可不可以呢？这对我帮助很大，多谢~

抱歉，我已经毕业，访问不了这些数据了。

**Comment by silence-tang** [comment]
好的好的，没关系。那我想问一下，PREPROCESSED_DATASET.md中没给出已经处理好的THUman4.0数据，那我是不是只需要执行GEN_DATA.md中Generate position maps.就可以处理得到好subject00所需的数据，然后执行python main_avatar.py -c configs/subject00/avatar.yaml --mode=train就可以开始训练了？另外整个训练过程大概需要多久呢？

**Comment by lizhe00** [comment]
> 好的好的，没关系。那我想问一下，PREPROCESSED_DATASET.md中没给出已经处理好的THUman4.0数据，那我是不是只需要执行GEN_DATA.md中Generate position maps.就可以处理得到好subject00所需的数据，然后执行python main_avatar.py -c configs/subject00/avatar.yaml --mode=train就可以开始训练了？另外整个训练过程大概需要多久呢？

对的，大概训练50万次迭代即可。

**Comment by silence-tang** [comment]
okok，谢谢。50w个iter需要时间大概多久呢，两三天够吗？

**Comment by lizhe00** [comment]
4090够的。

**Comment by silence-tang** [comment]
ok
