### ISSUE TITLE
Question About the  'pose_map' in 'avatar.py'

### ISSUE THREAD

**Issue by yzhzy1** [lizhe00/AnimatableGaussians#40]
Hello,

First of all, thank you for your excellent work on this project. I have been working with the avatar.py file and came across a line of code that I can't understand: `'pose_map = items['smpl_pos_map'][:3]' ` Could you please explain why [:3] is used here instead of just using the entire smpl_pos_map like this?` 'pose_map = items['smpl_pos_map']'` . My understanding is that pose_map should include both the front and back of the human body. Does [:3] serve a specific purpose that I'm missing?

Thank you for your time and assistance.

**Comment by lizhe00** [comment]
https://github.com/lizhe00/AnimatableGaussians/issues/22#issuecomment-2057056201

**Comment by yzhzy1** [comment]
oh, thank you  : )
