### ISSUE TITLE
How to make  calibration_full.json

### ISSUE THREAD

**Issue by Jun-Pu** [lizhe00/AnimatableGaussians#41]
Thanks for the inspiring work!

I would like to know by which tool you generate calibration_full.json for each avatar? 

Is the tool open-sourced?

Thx in advance!

**Comment by lizhe00** [comment]
Sorry, the calibration code dose not belong to me. It isn't open-sourced.

**Comment by Jun-Pu** [comment]
Well noted, thanks a lot
