### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement igl==2.2.1

### ISSUE THREAD

**Issue by ayutaz** [lizhe00/AnimatableGaussians#6]
### Description
When trying to install the required dependencies from the `requirements.txt` file, I encountered the following error:

```python
Collecting glfw==2.4.0 (from -r requirements.txt (line 1))
Using cached glfw-2.4.0-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38-none-manylinux2014_x86_64.whl.metadata (4.8 kB)
ERROR: Could not find a version that satisfies the requirement igl==2.2.1 (from versions: none)
ERROR: No matching distribution found for igl==2.2.1

This error occurs when trying to install the `igl` package at version 2.2.1, which appears to be listed in the `requirements.txt` file.
```

### Environments Tested
I have tried the following environments:

1. **venv** with Python 3.11
2. **Anaconda** with Python 3.10
3. **Anaconda** with Python 3.9

### Steps to Reproduce
1. Create a new virtual environment (using pyenv or Anaconda)
2. Install the required dependencies from the `requirements.txt` file

### Expected Behavior
All the dependencies listed in the `requirements.txt` file should be installed successfully without any errors.

### Additional Information
- cuda:12.2.0
- ubuntu22.04

Can you please let me know if you have an environment that works well for these errors?
Thank you in advance for your time.

**Comment by ayutaz** [comment]
@lizhe00 
Here's the English translation:

Could you provide the details of your environment? We would like to replicate the same environment on our end to investigate the issue.

Thank you.

**Comment by lizhe00** [comment]
Ubuntu 20.04.3
CUDA: 11.7
python: 3.8.17

**Comment by ayutaz** [comment]
Thank you.

**Comment by HarshWinterBytes** [comment]
I meet the same issue. Did you solve this problem?
My environment:
Ubuntu 22.04
CUDA: 11.3
python: 3.8.17

**Comment by lizhe00** [comment]
Hi @ayutaz @HarshWinterBytes , I have updated the requirements.txt. You can try it again.

**Comment by HJ1990** [comment]
> Hi @ayutaz @HarshWinterBytes , I have updated the requirements.txt. You can try it again.

A similar problem that I can't install pytorch3D==0.7.4. The error said 'Could not find the satisfied version of pytorch3D'.

**Comment by zhangdanq** [comment]
> > 你好@ayutaz @HarshWinterBytes，我已经更新了requirements.txt。你可以再试一次。
> 
> 类似的问题，我无法安装pytorch3D==0.7.4。错误提示“找不到满意的pytorch3D版本”。

你可以尝试使用源码安装或者conda安装

**Comment by janek** [comment]
I'm having the same issue as mentioned above (`ERROR: Could not find a version that satisfies the requirement pytorch3d==0.7.4 (from versions: none`). Perhaps it would be good to use `poetry` or `virtualenv` to manage dependency versions?
