### ISSUE TITLE
Training on our custum dataset and smpl_params.npz

### ISSUE THREAD

**Issue by se122811** [lizhe00/AnimatableGaussians#8]
Thank you for your excellent work and providing the codes.

I want to train on our own dataset. For the setting, how can I obtain smpl_params.npz? Should I use PyMAF-X as mentioned in the [AvatarRex](https://liuyebin.com/AvatarRex/)? If so, how can I tune the parameters to align it to the calibrated camera parameters (K[R|T])? I was curious about it because smpl parameters obtained from PyMAF-X are trained on fixed virtual camera (maybe focal length=(5000,5000) and extrinsic matrices are identity) across all the images.

I would appreciate it if you could answer.

**Comment by lizhe00** [comment]
We utilize the code from our lab for SMPL-X fitting. To the best of my knowledge, an open-sourced alternate is [EasyMocap](https://github.com/zju3dv/EasyMocap). But it requires you to transform the fitting results into `smpl_params.npz`.

**Comment by shengyuting** [comment]
大佬，calibration_full.json这个文件是怎么得到？是拍摄的机器导出来的吗 @lizhe00

**Comment by lizhe00** [comment]
> 大佬，calibration_full.json这个文件是怎么得到？是拍摄的机器导出来的吗 @lizhe00

这是标定文件，需要通过标定算法得到。

**Comment by shengyuting** [comment]
> > 大佬，calibration_full.json这个文件是怎么得到？是拍摄的机器导出来的吗 @lizhe00
> 
> 这是标定文件，需要通过标定算法得到。

有没有可以参考的标定方法，感谢！

**Comment by se122811** [comment]
Understood. Thank you for your kind response.

**Comment by se122811** [comment]
Understood. Thank you for your kind response.

Just one more question. Did you use multi-view fitting, or did you use single-view fitting for SMPL-X parameters? Or did you do fitting on monocular video like [video-based avatars](https://virtualhumans.mpi-inf.mpg.de/papers/alldieck2018video/alldieck2018videoshapes.pdf)? I would really appreciate your response.

Sincerely,

**Comment by lizhe00** [comment]
We use multi-view fitting because single view encounters depth ambiguity and occlusion.

**Comment by liwenssss** [comment]
have you tried to train and test your model on the DNA-Rendering dataset?

**Comment by lizhe00** [comment]
> have you tried to train and test your model on the DNA-Rendering dataset?

We haven't done this.

**Comment by se122811** [comment]
Thank you for your kindness :)

**Comment by silence-tang** [comment]
> transform the fitting results into `smpl_params.npz`

May I ask how to transform the fitting results into smpl_params.npz?

**Comment by IceFtv** [comment]
> > transform the fitting results into `smpl_params.npz`
> 
> May I ask how to transform the fitting results into smpl_params.npz?

Hi! I also want to know how to transform, have you solved this? If it's resolved, could you tell me the solution? Thanks.

**Comment by shengyuting** [comment]
Here is my method，the “content” is output from EasyMocap.
    smpl_data = {}
    smpl_data['betas'] = content['shapes']
    smpl_data['global_orient'] = np.zeros((size, 3))
    smpl_data['transl'] = np.zeros((size, 3))
    smpl_data['body_pose'] = content['poses'][:, :63]
    smpl_data['jaw_pose'] = content['poses'][:, 63:66]
    smpl_data['expression'] = np.zeros((size, 10))
    smpl_data['left_hand_pose'] = np.zeros((size, 45))
    smpl_data['right_hand_pose'] = np.zeros((size, 45))
    np.save('output/test_pose_refine.npy', smpl_data)

Uploading demo4.mp4…

**Comment by IceFtv** [comment]
Is your rendering result correct? I noticed that you have set both 'global_orient' and 'transl' to zero. In the output of easymocap, there are 'rh' and 'th', while smpl_params.npz does not. May I ask how you handled this? Thanks for your reply.

**Comment by shengyuting** [comment]
Here is my output.
https://github.com/lizhe00/AnimatableGaussians/assets/22219297/138c5ae5-0651-4892-8f37-9c39cc758b5e

**Comment by IceFtv** [comment]
It looks very great! Have you trained with the processed easymocap output? Have you trained with the processed easymocap output? Or are you just using it to infer new postures?  Thanks for your reply.

**Comment by shengyuting** [comment]
Just using it to infer.

**Comment by IceFtv** [comment]
谢谢你的回复。我想知道该如何正确处理并且用来训练，而将'global_orient' and 'transl' 置零的方法可能并不适用。请问这里有人正确使用处理后的easymocap的输出训练了吗？

**Comment by shengyuting** [comment]
你有自己拍摄的训练数据吗？ @IceFtv

**Comment by IceFtv** [comment]
暂时没有，我当前在尝试不使用任何数据集中拟合好的smplx参数，而去使用公开项目（easymocap）的结果。 @shengyuting

**Comment by shengyuting** [comment]
我'global_orient' and 'transl' 置零后，是通过导出easymocap的平移旋转矩阵来生成效果的，所以你可以看到我的结果里面人物可以旋转。 @IceFtv

**Comment by IceFtv** [comment]
能否加个联系方式详细聊一下。发完删除这个帖子。

**Comment by shengyuting** [comment]
WeChat：syt0321456

**Comment by shengyuting** [comment]
WeChat：syt0321456 @IceFtv

**Comment by silence-tang** [comment]
您好，请问我想把THuman4.0中的视频帧转换为512x512分辨率，该如何处理呢？谢谢！

**Comment by ZhenyanSun** [comment]
> 大佬，calibration_full.json这个文件是怎么得到？是拍摄的机器导出来的吗 @lizhe00

Hi silence-tange，have you found the solution to get the calibration_full.json? Could you share it, thx

**Comment by Abysswalker19** [comment]
> 谢谢你的回复。我想知道该如何正确处理并且用来训练，而将'global_orient' and 'transl' 置零的方法可能并不适用。请问这里有人正确使用处理后的easymocap的输出训练了吗？

Hello, have you found a way to use the output of easymocap to train yet?

**Comment by ddyj** [comment]
> [EasyMocap](https://github.com/zju3dv/EasyMocap)。但它需要你将拟合结果转换为`smpl_params.npz`.

大佬 这个是怎么转化的呀

**Comment by ddyj** [comment]
> 谢谢你的回复。我想知道该如何正确处理并且用来训练，而将'global_orient' and 'transl' 置零的方法可能并不适用。请问这里有人正确使用处理后的easymocap的输出训练了吗？

请问您解决了吗

**Comment by zhiyw120547** [comment]
@shengyuting 您好， 可以请问一下怎么导出平移旋转矩阵吗？是在置零后global_orient= Rh 还是通过R'@R和R'@T + T'计算出来的啊
> 我'global_orient'和'transl'置零后，是通过导出easymocap的平移旋转矩阵来生成效果的，所以你可以看到我的结果里面的人物可以旋转。[@IceFtv](https://github.com/IceFtv)

**Comment by ZJun96** [comment]
需要改的3个文件：
gen_weight_volume.py
gen_pos_maps.py
dataset_mv_rgb.py

1）把所有地方读取”smpl_params.npz“的代码全部改成读取自己的smplx数据

2）smplx.SMPLX()，改成自己的参数，但关键的一个参数“flat_hand_mean=True”一定要加上，这个是生成原文自定义的一个大字型template的关键。
例如：
根据我自己的身体参数betas，脸部参数expression数量设置num_betas，num_expression_coeffs；
我的手部使用了pca，压缩后参数是12个。use_pca=True,num_pca_comps=12；
有的可能body_pose会用VPoser decode，根据自己的代码转一下，然后smpl_model.forward() 使用转制后的参数。
smpl_model = smplx.SMPLX(
        model_path=os.path.join(model_dir, "smplx"),
        ext='npz',
        gender=gender,
        num_betas=betas_np.shape[-1],
        num_expression_coeffs=num_expr,
        use_face_contour=False,
        use_pca=True,          
        num_pca_comps=12, 
        flat_hand_mean=True
    )

3）cano_smpl部分基本不需要去动，config.py文件里面写好了cano_smpl的身体姿势，一个大字型人体
cano_smpl = self.smpl_model.forward(
                betas = self.smpl_data['betas'][0][None],
                global_orient = config.cano_smpl_global_orient[None],
                transl = config.cano_smpl_transl[None],
                body_pose = config.cano_smpl_body_pose[None],
                jaw_pose = self.smpl_data['jaw_pose'][pose_idx][None],
                expression = self.smpl_data['expression'][pose_idx][None],
            )

4）相机加载在dataset_mv_rgb.py里，加一个自己数据库的类，函数改成读取自己相机文件然后构建相机。

5）最后，改完后加一些检查脚本，特别是相机，坐标系等的转换，务必保证smplx投影到gt的时候位置正确，再开始生成template和avatar重建

**Comment by xkkjiayou** [comment]
感谢您的来信，此时我不在办公室，稍后会及时阅读。在此期间我不方便接收邮件。如果您想及时获得通讯，请拨打我的手机联系我，谢谢您。
