### ISSUE TITLE
Possible code errors in raster settings

### ISSUE THREAD

**Issue by tb2-sy** [lizhe00/AnimatableGaussians#9]
In line 52 of gaussian_renderer.py, `camera_center = torch.linalg.inv(extr)[:3, 3] `seems to be changed to camera_center = `torch.linalg.inv(extr)[3, :3]`, although judging from the results It seems to have little impact.

**Comment by lizhe00** [comment]
`torch.linalg.inv(extr)[3, :3]` is zero, because the translation vector is at the upper right corner of `extr`. You can print both `torch.linalg.inv(extr)[:3, 3]` and `torch.linalg.inv(extr)[3, :3]` to check them.

**Comment by tb2-sy** [comment]
> `torch.linalg.inv(extr)[3, :3]` is zero, because the translation vector is at the upper right corner of `extr`. You can print both `torch.linalg.inv(extr)[:3, 3]` and `torch.linalg.inv(extr)[3, :3]` to check them.

Thanks for the reply. I made a mistake. The code is `torch.linalg.inv(extr)[:3, 3]` instead of using the transposed world_view_transform to find the inversion.
